apiVersion: v1
kind: Namespace
metadata:
  name: llm-embedded-cluster
  labels:
    name: llm-embedded-cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-chatbot-backend-embedded
  namespace: llm-embedded-cluster
  labels:
    app: llm-chatbot
    component: backend
    model-type: "embedded"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-chatbot
      component: backend
  template:
    metadata:
      labels:
        app: llm-chatbot
        component: backend
        model-type: "embedded"
    spec:
      containers:
      - name: backend
        image: llm-chatbot-backend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "kubernetes-embedded"
        - name: PORT
          value: "8000"
        - name: LLM_MODEL_PROVIDER
          value: "ollama"
        - name: LLM_MODEL_NAME
          value: "llama3.2"
        - name: LLM_BASE_URL
          value: "http://localhost:11434"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30

      - name: ollama-embedded
        image: ollama-with-llama32:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 11434
          name: ollama-http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        - name: OLLAMA_PORT
          value: "11434"
        - name: OLLAMA_MODELS
          value: "/root/.ollama/models"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 3Gi
        readinessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 20
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: llm-chatbot-backend-service-embedded
  namespace: llm-embedded-cluster
  labels:
    app: llm-chatbot
    component: backend
    model-type: "embedded"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30091
    name: http
  selector:
    app: llm-chatbot
    component: backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm-chatbot-backend-embedded-hpa
  namespace: llm-embedded-cluster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-chatbot-backend-embedded
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 