apiVersion: v1
kind: Namespace
metadata:
  name: llm-gpu-cluster
  labels:
    name: llm-gpu-cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-chatbot-backend-fast
  namespace: llm-gpu-cluster
  labels:
    app: llm-chatbot
    component: backend
    variant: fast
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-chatbot
      component: backend
  template:
    metadata:
      labels:
        app: llm-chatbot
        component: backend
        variant: fast
    spec:
      containers:
      # FastAPI Backend
      - name: backend
        image: llm-chatbot-backend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: PORT
          value: "8000"
        - name: LLM_MODEL_PROVIDER
          value: "ollama"
        - name: LLM_MODEL_NAME
          value: "llama3.2:1b"
        - name: LLM_BASE_URL
          value: "http://localhost:11434"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30

      # Ollama Sidecar with optimized startup
      - name: ollama
        image: ollama-with-models:local
        imagePullPolicy: Never
        ports:
        - containerPort: 11434
          name: ollama-http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        - name: OLLAMA_PORT
          value: "11434"
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        readinessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 30
        # Post-start hook to load models quickly
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                sleep 10
                ollama pull llama3.2:1b &
                ollama pull phi3:mini &
                wait

---
apiVersion: v1
kind: Service
metadata:
  name: llm-chatbot-backend-service-fast
  namespace: llm-gpu-cluster
  labels:
    app: llm-chatbot
    component: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30083
    name: http
  selector:
    app: llm-chatbot
    component: backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm-chatbot-backend-hpa-fast
  namespace: llm-gpu-cluster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-chatbot-backend-fast
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 