apiVersion: v1
kind: Namespace
metadata:
  name: llm-gpu-cluster
  labels:
    name: llm-gpu-cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-chatbot-backend-gpu
  namespace: llm-gpu-cluster
  labels:
    app: llm-chatbot
    component: backend
    gpu-optimized: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llm-chatbot
      component: backend
  template:
    metadata:
      labels:
        app: llm-chatbot
        component: backend
        gpu-optimized: "true"
    spec:
      containers:
      - name: backend
        image: llm-chatbot-backend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: ENVIRONMENT
          value: "kubernetes-native"
        - name: PORT
          value: "8000"
        - name: LLM_MODEL_PROVIDER
          value: "ollama"
        - name: LLM_MODEL_NAME
          value: "llama3.2:1b"
        - name: LLM_BASE_URL
          value: "http://localhost:11434"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30

      - name: ollama-llm
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
          name: ollama-http
        env:
        - name: OLLAMA_HOST
          value: "0.0.0.0"
        - name: OLLAMA_MODELS
          value: "/models"
        resources:
          requests:
            cpu: 1000m
            memory: 3Gi
          limits:
            cpu: 4000m
            memory: 6Gi
        volumeMounts:
        - name: ollama-models
          mountPath: /models
        - name: model-init
          mountPath: /init
        readinessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/version
            port: 11434
          initialDelaySeconds: 60
          periodSeconds: 30

      initContainers:
      - name: model-downloader
        image: ollama/ollama:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "🚀 Downloading LLM models for Kubernetes deployment..."
          ollama serve &
          sleep 10
          
          echo "📦 Pulling llama3.2:1b model..."
          ollama pull llama3.2:1b
          
          echo "📦 Pulling phi3:mini model..."
          ollama pull phi3:mini
          
          echo "✅ Models downloaded successfully!"
          ls -la ~/.ollama/models/
        env:
        - name: OLLAMA_MODELS
          value: "/models"
        volumeMounts:
        - name: ollama-models
          mountPath: /models
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi

      volumes:
      - name: ollama-models
        emptyDir:
          sizeLimit: 10Gi
      - name: model-init
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: llm-chatbot-backend-service-gpu
  namespace: llm-gpu-cluster
  labels:
    app: llm-chatbot
    component: backend
    gpu-optimized: "true"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30090
    name: http
  selector:
    app: llm-chatbot
    component: backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: llm-chatbot-backend-hpa
  namespace: llm-gpu-cluster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: llm-chatbot-backend-gpu
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 