apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-chatbot-frontend-fast
  namespace: llm-gpu-cluster
  labels:
    app: llm-chatbot
    component: frontend
    variant: fast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-chatbot
      component: frontend
  template:
    metadata:
      labels:
        app: llm-chatbot
        component: frontend
        variant: fast
    spec:
      containers:
      - name: frontend
        image: llm-chatbot-frontend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "http://llm-chatbot-backend-service-fast"
        - name: REACT_APP_WS_URL
          value: "ws://llm-chatbot-backend-service-fast"
        - name: BACKEND_SERVICE_NAME
          value: "llm-chatbot-backend-service-fast.llm-gpu-cluster.svc.cluster.local:80"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: llm-chatbot-frontend-service-fast
  namespace: llm-gpu-cluster
  labels:
    app: llm-chatbot
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30084
    name: http
  selector:
    app: llm-chatbot
    component: frontend 