name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: llm-chatbot-cluster
  GKE_ZONE: us-central1-a
  DEPLOYMENT_NAME: llm-chatbot-backend
  IMAGE: llm-chatbot-backend
  
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    # Configure Docker to use the gcloud command-line tool as a credential helper
    - name: Configure Docker for GCP
      run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Build the Docker image
    - name: Build Docker image
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:latest" \
          .

    # Push the Docker image to Google Container Registry
    - name: Publish Docker image
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
        docker push "gcr.io/$PROJECT_ID/$IMAGE:latest"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy to GKE
      run: |-
        # Apply basic resources first
        kubectl apply -f k8s/rbac.yaml
        kubectl apply -f k8s/configmap.yaml
        
        # Create secrets if they don't exist
        kubectl create secret generic llm-chatbot-secrets \
          --from-literal=openai_api_key="${{ secrets.OPENAI_API_KEY }}" \
          --dry-run=client -o yaml | kubectl apply -f -
        
        # Update the deployment image
        kubectl set image deployment/$DEPLOYMENT_NAME backend=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        
        # Apply other resources
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/hpa.yaml
        
        # Verify deployment
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide

  test-deployment:
    name: Test Deployment
    runs-on: ubuntu-latest
    needs: setup-build-publish-deploy
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Get GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Test deployment
      run: |-
        # Wait for pods to be ready
        kubectl wait --for=condition=ready pod -l app=llm-chatbot --timeout=300s
        
        # Get service info
        kubectl get pods,services,hpa -l app=llm-chatbot
        
        # Test health endpoint
        kubectl run test-curl --image=curlimages/curl:latest --rm -i --restart=Never -- \
          curl -f http://llm-chatbot-backend-service/health
        
        echo "Deployment test completed successfully!"

  cleanup-on-failure:
    name: Cleanup on Failure
    runs-on: ubuntu-latest
    needs: setup-build-publish-deploy
    if: failure()
    
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Rollback on failure
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        kubectl rollout undo deployment/$DEPLOYMENT_NAME || echo "No previous revision to rollback to" 